### ISSUE TITLE
Cannot connect to the proxy server.

### ISSUE THREAD

**Issue by valicu001** [TheKronks/KRelay#42]
When I try to play on the proxy server,the k-relay gives me the following error:

[Error]          An exception was thrown
within PacketSend (packet = DEATH) 
at <>c__DisplayClass38_0.<Send>b__0

System.NullReferenceException: Object reference not set to an instance of an object.
   at Lib_K_Relay.Networking.Client.<>c__DisplayClass38_0.<Send>b__0() in E:\K_Relay-master\Lib K Relay\Networking\Client.cs:line 176
   at Lib_K_Relay.Utilities.PluginUtils.ProtectedInvoke(Action action, String errorProvider, Type filteredException) in E:\K_Relay-master\Lib K Relay\Utilities\PluginUtils.cs:line 38
[Client]         Disconnected.
[Error]          An exception was thrown
within RemoteRead (isClient = True) 
at NetworkStream.BeginRead

System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.NetworkStream'.
   at System.Net.Sockets.NetworkStream.BeginRead(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   at Lib_K_Relay.Networking.Client.BeginRead(Int32 offset, Int32 amount, Boolean client) in E:\K_Relay-master\Lib K Relay\Networking\Client.cs:line 188
   at Lib_K_Relay.Networking.Client.<>c__DisplayClass40_0.<RemoteRead>b__0() in E:\K_Relay-master\Lib K Relay\Networking\Client.cs:line 235
   at Lib_K_Relay.Utilities.PluginUtils.ProtectedInvoke(Action action, String errorProvider, Type filteredException) in E:\K_Relay-master\Lib K Relay\Utilities\PluginUtils.cs:line 38
[Listener]       Client received.

**Comment by EinarasGar** [comment]
First of all, did you update packets.xml?
